### ISSUE TITLE
Example of inference of model

### ISSUE THREAD

**Issue by WuZhuoran** [swook/GazeML#23]
Hi,

I already checked #7  for gaze inference, but i still do not know how to load the model and apply model on a single image and get the output.

```python
infer = model.inference_generator()
output = next(infer)
# Then deal with output.
```

It seems that you use an inference generator. Do you have something easier to use?

Such as
```python
model = DPG.load('model weights')
image = cv2.imread('image path')

output = model.predict(image)
```

Just like that,

Thank you so much.

**Comment by WuZhuoran** [comment]
Of course, in tensorflow, it could be:

```python
with tf.Session(...) as sess:
    tf.saved_model.loader.load(sess, ...)
    sess.run('myOutput:0',
               feed_dict={'myInput:0': ...
```

**Comment by WuZhuoran** [comment]
I found the code in inverence_generator.py

```python
data_source = next(iter(self._train_data.values()))
while True:
      fetches = dict(self.output_tensors['train'], **data_source.output_tensors)
      start_time = time.time()
      outputs = self._tensorflow_session.run(
      fetches=fetches,
       feed_dict={
            self.is_training: False,
            self.use_batch_statistics: True,
        },
       )
     outputs['inference_time'] = 1e3*(time.time() - start_time)
      yield outputs
```

This fetch from datasource, right? How about for a single image? could we inference with out put image into datasource?

Thank you

**Comment by WuZhuoran** [comment]
According to your paper and output or training, there are 2 models, first is hourglass, the other is densenet. Now I already trained the models. How to load and run?

Thank you for your help.

**Comment by swook** [comment]
Hi many apologies for taking so long to reply to this...

To be honest it's because I don't have a straight-forward solution for a simple way to do inference. What I recommend is to copy the model code to a simpler code-base for yourself, then load the checkpoints.

I use `tf.Saver` to load model parameters. See https://github.com/swook/GazeML/blob/master/src/core/checkpoint_manager.py#L47

The restoring occurs based on the `tf.variable_scope` definitions and thus naming of various tensors. So I recommend keeping the neural net spec. as it is.

**Comment by parai** [comment]
Hi:
I have created a DMS demo that use GazeML, here is the code that show how GazeML was used, https://github.com/parai/dms/blob/master/models/gaze.py.

**Comment by yuqwang913** [comment]
Hi! I am also facing with same problem. How do you fix it?
